turingschool/frontend-lightning-talks

schedule-1703.md
This is the topic I'd like to do. Hopefully I got there first :)
=> George Goering: Algorithms or Die - top algorithms programmers should know

schedule-1703.md
Let me know if that doesn't work out! Thank you
=> Sasha Dunbar: Javascript- closures

schedule-1703.md
Choosing a topic for lightning talks.
=> Jason Collins: Pairing approaches - all the types and pros/cons

schedule-1703.md
Shayla Richard : Developer Identity
=> Shayla Richard : Developer Identity

schedule-1703.md
Algorithms or die - top algorithms programmers should know
Seems, rad.
=> Evan Miller: D3

schedule-1703.md
I would like to talk on this topic if not taken already.
=> Ralph Burnette: Hacking the FE interview

schedule-1705.md
Requesting "Breaking the problem down + best pseudo coding practices” as topic for my lightning talk
=> Laura Caroselli: Breaking the problem down + best pseudo coding practices”

schedule-1705.md
=> TALK CHOICES

schedule-1706.md
=> mr lightning talk

schedule-1706.md
David Ryan: React ES6 or Canvas
=> David Ryan: React ES6 or Canvas

schedule-1706.md
=> Sam Singer Topic Update

schedule-1706.md
I'd like to talk about the D3.js library for my lightning talk on Thursday.
=> Adam Mescher Lightning Talk Topic Proposal

README.md
I would like to do my lightning talk on SEO.
=> Ben Porter Lightning Talk

schedule-1708.md
Client side security + hacking
=> Thomas Laird: Client side security + hacking

schedule-1708.md
Explain the awesome power that is HTML canvas.
=> patrick-neel HTML Canvas

schedule-1708.md
Brandon Farestad-Rittel: Breaking the problem down + best pseudo coding practices
=> Brandon Breaking the problem down + best pseudo coding practices.md

schedule-1708.md
how HTML-canvas can produce vivacious animations to animate a drawing and objectify your drawing
=> patrick-neel HTML-canvas

schedule-1708.md
I'd like to do a lightning talk about using Electron
=> Jesse Packwood-1708.md

schedule-1708.md
I added my new lightning talk topic
=> add my lightning talk topic

schedule-1708.md
Hello! This is the topic that I would LOVE to talk about, thanks!
=> jQuery chaining - the good, the bad, the ugly

schedule-1708.md
Allison covered what I was going to say so I changed to Front End Landscape, where I will talk about what is it like out there (jobwise) for front end devs
=> Change of topic

schedule-1710.md
Media queries - screens + beyond - JEFF GOODALL
=> Jeff Goodall 

schedule-1710.md
Michelle Hoffman: CSS Styleguides
=> Add preference for lightning talks

schedule-1710.md
sabrina -kennedy :CSS relative units of measure: ems, rems, percentages, viewport measures
=> sabrina-kennedy

schedule-1710.md
I would like to do a lightening talk on Hacking the FE interview
=> Casey Dallavalle to option 30

schedule-1710.md
Ricardo Viera's attempt at picking a topic for lightning talk. 
I'm picking Javscript Prototypes as it's a subject I think I'm struggling with.
=> Ricardo Viera - Javascript Function Prototypes

schedule-1711.md
=> Patrick McLaughlin React What and Why

schedule-1711.md
I picked linters!!!!!!!@!@@@!!
=> Edgar's lightning talk

schedule-1711.md
Going beyond Bitcoin to understand blockchain technology.
=> Matt Walker: Beyond Bitcoin. Blockchain technology

schedule-1711.md
Client side security and hacking
=> Ryan Harrington

schedule-1711.md
Not sure if the first one went away.
=> Megan second choice

schedule-1801.md
Breaking the problem down + best pseudo coding practices
=> Add Camilo LT

schedule-1801.md
Assigned the topic for Tony Robertson.
=> Topic for Tony Robertson

schedule-1803.md
Add a new topic to topic selection list: Building a Website in Layers: Leveraging the Z-Index and Opacity for Visual Interest.
=> Add topic 31 to topic selection list

schedule-1803.md
7.  Joel O'Connor: CSS positioning - all the techniques, pros/cons, results
=> Joel O'Connor 7.  CSS positioning - all the techniques, pros/cons, results Update schedule-1803.md

schedule-1806.md
=> My topic request

schedule-1806.md
First choice - 
Cole Hart - HTML Canvas
Second Choice - 
Cole Hart - D3 Library
=> Cole Hart - HTML Canvas

schedule-1806.md
Looks like I didn't get me first choice, so can I change to Linters for the Lightning Talk.
=> Tobin Nelson -Linters

schedule-1806.md
=> Lightning Talk

schedule-1806.md
=> WTF Webpack

schedule-1808.md
=> Loryn Mason CSS relative units of measure

schedule-1808.md
Signed up for Hacking the FE interview.
=> Ashley Levi: Hacking the FE interview

schedule-1808.md
Elly Torres: Algorithms or Die!! - top algorithms programmers should know
=> ellyTorres-AlgorithmsOrDie

schedule-1808.md
=> Update schedule-1808.md Matt Franzen: ARPANET

schedule-1808.md
Talk about what user research is and how it plays a part in making a great user experience.
=> Paul Vangelakos - User research is at the heart of designing a good user experience.

schedule-1901.md
21  Pairing approaches - all the types and pros/cons
=> Kayla Lawson 21  pairing approaches

schedule-1901.md
=> Melissa LaChasse - 30

schedule-1901.md
=> Kevin Krato - ES6

schedule-1901.md
CSS positioning - all the techniques, pros/cons, results - Emily
=> Emily Dittmer - CSS positioning

schedule-1901.md
=> Mark — web scrapers

schedule-1901.md
=> Jonathan Keever

schedule-1901.md
=> Lauren-HTML canvas

schedule-1904.md
Emily Lalonde: React - what and why?
=> Emily Lalonde: React - what and why?

schedule-1904.md
1) Annie Goodwin - Pairing approaches - all the types and pros/cons
2) Annie Goodwin - Object Oriented Programming
=> Annie Goodwin - Pairing approaches - all the types and pros/cons

schedule-1904.md
2nd choice
24. Breaking the problem down + best pseudo coding practices
=> 22. Amy Rippeto - Tips for crafting your “Developer Identity”

schedule-1904.md
=> Garrett Iannuzzi: WTF Webpack? And why do I care?

schedule-1904.md
Gregory Anderson - What is VIM
=> Gregory Anderson - What is VIM

schedule-1904.md
=> Brandy: Object Oriented Programing

schedule-1904.md
Alternatives: 
20. Front End Hip - how to stay in the know on all the things
23. Team collaboration: github/PR etiquette, good workflows, best practices
=> Alyssa Lundgren: Tips for crafting your “Developer Identity”

schedule-1904.md
If not available, I'd like to do the "Javascript 'this' binding" topic.
=> Naomi Campos - Object Oriented Programming

schedule-1904.md
If HTML canvas is unavailable, I am fine presenting on Webscrapers, Linters, or Hacking the FE Interview.
=> Eric O'Neill: HTML Canvas

schedule-1904.md
I would like to do my lightening talk on jQuery chaining - the good, the bad, the ugly.
=> Yana Aleksandrova jQuery chaining - the good, the bad, the ugly

schedule-1904.md
Javascript - closures 
What is this VIM you speak of?
Media queries - screens + beyond.
Some back up choices just in case.
=> Colin - Javascript - closures

schedule-1904.md
=> David Gitlen: Linters

schedule-1904.md
I find this topic much more interesting and engaging for its visual character. Please switch me to this topic instead )
=> Yana Aleksandrova D3 library

schedule-1904.md
Travis and Khalid have thumbs up this topic. Cheers!
=> Lacy Rudd - Intro to SEO

schedule-1904.md
Approved by Travis to change my topic!
=> Update schedule-1904.md - Samantha Freeman

schedule-1906.md
=> Allison Wagner: ES6-1906.md

schedule-1906.md
I would like to do my talk on react if thats possible. Thanks!
=> Noah - react

schedule-1906.md
I would like to talk on Webpack.
=> Talk Choice: WTF Webpack? And why do I care?

schedule-1906.md
Preference in order is:
React - what and why?
Object Oriented Programming
Linters - what, why, how, types?
=> Vanessa Randall Update schedule-1906.md

schedule-1906.md
ES 6 was gone. If not jQuery I would like hacking the interview.
=> Garrett Iannuzzi: jQuery changing

schedule-1906.md
-Github etiquette
-Client side security
=> Pol Sieira: Linters

schedule-1906.md
Would love to talk on any of the subjects.  If this one doesn't work out, let me know what's left and I'll take it!
=> Annie - Tips for crafting your developer identity

schedule-1906.md
=> Sara Karsh :What is this VIM you speak of?

schedule-1906.md
Top three choices are:
1. Client Side Security + Hacking
2. ES6
3. Algorithms or Die - top algorithms programmers should know
=> jEduardo.md

schedule-1906.md
=> Brady - Recursion

schedule-1906.md
Added new talk topic to the bottom of the list!
=> Quinne: The Golden Ratio

schedule-1906.md
Back-up topics:
1. Front End Hip
2. Algorithms or die
3. Breaking the problem down
=> Michael Schneider: JavaScript - Closures

schedule-1906.md
1.  - 20. FE hip 
2. - 33. Stat vs Dynamic
3. - 30. Hacking the FE interview
4. - 15. HTML canvas
=> Kate Malone - FE hip

README.md
=> Roger Hughes 14. D3 library

schedule-1906.md
=> Sam Coleman - FE interview

schedule-1906.md
My newly proposed lightning talk about the use of github in the tech industry job search process.
=> Zoë Ketcham-Harvey: Github and the new tech resume
